/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.moodtest;

import org.junit.Test;
import com.capgemini.mood.MoodAnalyzer;
import com.capgemini.mood.MoodAnalyzerException;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class MoodAnalyzerTest {
	@Test
	public void TestMoodAnalysisEnteredEmpty() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer("");
		try {
			moodAnalyzer.analyseMood();
		} catch (MoodAnalyzerException e) {
			Assert.assertEquals(MoodAnalyzerException.ExceptionType.ENTERED_EMPTY, e.type);
		}
	}

	@Test
	public void TestMoodAnalysisEnteredNull() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer(null);
		try {
			moodAnalyzer.analyseMood();
		} catch (MoodAnalyzerException e) {
			Assert.assertEquals(MoodAnalyzerException.ExceptionType.ENTERED_NULL, e.type);
		}
	}

	@Test
	public void TestMoodAnalysisAnyMood() throws MoodAnalyzerException {
		MoodAnalyzer moodAnalyser = new MoodAnalyzer();
		String mood = moodAnalyser.analyseMood("I am in Any mood");
		Assert.assertEquals("HAPPY", mood);
	}

	@Test
	public void TestMoodAnalysisSadMood() throws MoodAnalyzerException {
		MoodAnalyzer moodAnalyser = new MoodAnalyzer();
		String mood = moodAnalyser.analyseMood("I am in sad mood");
		Assert.assertEquals("SAD", mood);
	}

	@Test
	public void TestMoodAnalysisHappyMood() throws MoodAnalyzerException {
		MoodAnalyzer moodAnalyser = new MoodAnalyzer();
		String mood = moodAnalyser.analyseMood("I am in happy mood");
		Assert.assertEquals("HAPPY", mood);
	}
}
